const riscani1 = [
  {
    id: 82,
    name: "Instituția Publică Liceul Teoretic „Nicolae Bălcescu”",
    schoolAdress: "com. Ciorescu, Str. Al. cel Bun, 10",
    sector: "com. Ciorescu",
    phone: "+373 22 457848",
    freePlaces: 90,
    freePlacesLyceum: 40,
    serviceAdress: [
      "Instituţia efectuează înscrierea copiilor în clasa I din districtul comunelor Ciorescu, Făureşti, Goianii  și Goianul Nou",
    ],
    requestsSent: 192,
    freePlacesProfiles: {
      second_tour_places: 58,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 93,
    name: 'Liceul Teoretic "George Călinescu"',
    schoolAdress: "str. Ceucari, 7",
    sector: "Râșcani",
    phone: "+373 22 466923",
    freePlaces: 180,
    freePlacesLyceum: 60,
    serviceAdress: [
      "Str. Socoleni ",
      "Str. Ceucari ",
      "Str. Grătieşti ",
      "Str. Iazului ",
      "Str. Cucorilor ",
      "Str-la Studenţilor ",
      "Str. Gheorghe Madan 46 până la sfârșit",
      "Str. Doina de la  121 - până la sfârşit                                      ",
      "Str. V. Crăsescu 59-299, 52-300 ",
      "Str- la V. Crăsescu 36-88, 37-87 ",
      "Str. Criuleni 60-82, 67-85 ",
      "Str-la Criuleni 40-60; 45-61",
      "Str-la Circului 40-60, 45-63",
      "Str. L. Damian-60-82, 59-81",
      "Str. Podgorenilor 86-200",
      "Str. Moldoviţa 20 până la capăt (numere pare)",
      "Str-la Liviu Damian ",
      "Calea Orheiului 109-113, 90, 90 a, ...",
      "Str. Pitulicii 26-32, 13-29, 37...",
    ],
    requestsSent: 151,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 21,
    name: 'Instituția Publică Liceul Teoretic „Academia Copiilor" ',
    schoolAdress: "str. Albişoara, 16/3",
    sector: "Râșcani",
    phone: "+373 22 540610",
    freePlaces: 75,
    freePlacesLyceum: 44,
    serviceAdress: ["Str.Ismail 88-108", "Str.Albişoara 8-22 "],
    requestsSent: 92,
    freePlacesProfiles: {
      second_tour_places: 65,
      second_tour_places_lyceum: 17,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 60,
    name: "Instituție Publică Liceul Teoretic „Ion Creangă”",
    schoolAdress: "str. Studenţilor, 10/3",
    sector: "Râșcani",
    phone: "+373 22 325335",
    freePlaces: 120,
    freePlacesLyceum: 90,
    serviceAdress: [
      "Str. Studenţilor 3/2, 3/6, 3/10, 7/1, 7/2, 7/3, 7/7, 7/8, 7/9, 7/10, 7/11 9/18, 9/19, 9/20, 9/21, 9/22, 9/23, 10/1, 10/2, 12/1, 12/2, 12/3,12/4 ",
      "Bulevardul Moscovei 20,  20/2, 20/3, 20/4, 22, 22/2, 24, 26, 26/2, 28 ",
      "Str. Dimo 29/1, 29/2, 29/3, 29/4, 31, 31/1, 31/2, 32",
      "Str. Primar Gherman Pîntea 3-229, 102-142 ",
      "Str-la Primar Gherman Pîntea ",
      "Str. Academician Sergiu Rădăuţanu 3, 5, 7, 9, 11 ... până la sfârșit",
      "Str. Lidia Istrati ",
      "Str. Petru Leşcenco ",
      "Str-la Petru Leşcenco ",
      "Str. Olga Vrabie ",
      "Str-la 1 Olga Vrabie ",
      "Str-la 2 Olga Vrabie",
      "Str. Bucovinei 18/6",
    ],
    requestsSent: 193,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 95,
    name: 'Liceul Teoretic "Waldorf" ',
    schoolAdress: "str. Studenților, 11",
    sector: "Râșcani",
    phone: "+373 22 323155",
    freePlaces: 60,
    freePlacesLyceum: 5,
    serviceAdress: ["f/d"],
    requestsSent: 104,
    freePlacesProfiles: {
      second_tour_places: 1,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 62,
    name: 'Instituția Publică Liceul Teoretic "Mihail Kogâlniceanu"',
    schoolAdress: "str. Miron Costin, 3",
    sector: "Râșcani",
    phone: "+373 22 441302",
    freePlaces: 100,
    freePlacesLyceum: 50,
    serviceAdress: [
      "Str. Studenţilor 1, 1/1, 3, 3/1, 5, 5/1, 2, 4",
      "Str. Miron Costin 1/1, ½, 1/3, 3/1, 5/1, 11/2, 11/3, 11/3a, 11/4",
      "Str. Florilor 12 A, 12/1, 12/2, 12/3, 12/4, 14/1, 14/2, 16/1, 16/2, 16/3, 18/1,18/2, 26-32, 32/1, 32/2, 34/1",
      "Bd. Moscovei 9/5, 11, 11/1, 11/5, 11/8, 13, 13/2, 13/3, 13/3a, 13/4, 13/5, 15/1, 15/2, 15/3, 15/6, 17/1, 17/2, 17/3 ",
      "Str. Matei Basarab 1, 1/1,  1/3,  2, 2/1, 6, ",
      "str. Academician Eugen Coșeriu 8, 3, 17, 17/1- toate",
      "str. Emil Loteanu",
      "str. Pavel Barbalat",
      "str. Andrei Ciurunga",
      "str. Constantin Constantinov",
      "str. Academician Silviu Berejan",
      "str. Vasile Țepordei",
      "str. Academician Nicolae Corlăteanu",
      "str. Eugen Rusev",
      "str. Operațiunea Iași-Chișinău",
      "str. Dumitru Gheorghiță",
      "str. Gherman Pîntea 12-64",
    ],
    requestsSent: 199,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 55,
    name: 'Liceul Teoretic „George Meniuc"',
    schoolAdress: "str. Albişoara, 84",
    sector: "Râșcani",
    phone: "+373 22 291228",
    freePlaces: 130,
    freePlacesLyceum: -18,
    serviceAdress: [
      "Str. Albişoara 64-86 ",
      "Str. Sf. Ilie ",
      "Str. Zaichin ",
      "Str. Căpriana ",
      "Str. B. P. Hajdeu ",
      "Str. Sf. Andrei ",
      "Str. Cantonului 2-20 ",
      "Str. Ion Doncev ",
      "Str. Ion Pruncul ",
      "Str. Botezatu Andrei ",
      "Str. Petricani ",
      "Str. Moara Roşie ",
      "Str. Buna Vestire ",
      "Str. Colina Puşkin ",
      "Str. Constantin Stamati 2-10 ",
      "Str. Zamfir Arbore ",
      "Str. Mirceşti ",
      "Str. Maria Cibotaru 63-69 ",
      "Str. S. Lazo 21-29, 50 ",
      "Str. Sfatul Ţării 32-300, 63-299 ",
      "Str. Columna 112-154 ",
      "Str. Alexandru cel Bun 91-117, 100-300",
      "Str. Bănulescu Bodoni 51-299",
      "Str. Anton Pan 9, 11 ",
      "Str. Movila lui Burcel ",
      "Str. Cramei",
      "Str. Petru Rareş ",
      "Str-la Pescaruşilor ",
      "Str-la Arhanghelul Mihail",
      "Str-la Codrul Cozminului",
      "Str. Căpriana",
      "Str. Romană",
      "Str. Buna vestire",
      "Str. Mihai Viteazul 78",
      "Str. Străşeni",
      "Str. Ipoteşti",
      "Str. A. Belski",
      "Str. Astronom Nicolae Donici",
      "Str. T Panfile",
      "Str. Memoriei",
      "Str. Valea Albă",
      "Str. Zamolxe",
      "Str. Voluntar Filip Lupaşcu",
      "Str. Volunta Gh. Vîrtosu ",
      "Str. Vasile Harea ",
      "Str. Spicului",
      "Str. Vasile Harea",
      "Str. Domniței",
      "Str. Gura Văii",
      "Bl. Grigore Vieru 13-29",
      "Str.N.Berzarin  ",
      "Str.S.Timoșenco ",
      "Str.F.Tolbuhin  ",
      "Str.S.Coipan ",
      "Șos. Balcani 7/2-7/5",
    ],
    requestsSent: 137,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 6,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 111,
    name: 'Instituție Publică Liceul Teoretic "Grătiești"',
    schoolAdress: "str. Ștefan cel Mare, 17",
    sector: "Grătiești",
    phone: "+373 22 451154",
    freePlaces: 70,
    freePlacesLyceum: 40,
    serviceAdress: [
      "Instituţia efectuează înscrierea copiilor în clasa I din comuna Grătieşti",
    ],
    requestsSent: 50,
    freePlacesProfiles: {
      second_tour_places: 4,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 25,
    name: 'Liceul Teoretic „Vasil Levski"',
    schoolAdress: "str. Studenţilor, 3/3",
    sector: "Râșcani",
    phone: "+373 22 319129",
    freePlaces: 50,
    freePlacesLyceum: 50,
    serviceAdress: [
      "Str. Lidia Istrati ",
      "Str. Petru Leşcenco ",
      "Str-la Petru Leşcenco ",
      "Str. Olga Vrabie ",
      "Str-la 1 Olga Vrabie ",
      "Str-la 2 Olga Vrabie",
      "Str. Valentin Roșca",
      "Str. Studenţilor 3/2, 3/6, 7/3, 7/4, 7/7",
    ],
    requestsSent: 34,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 91,
    name: "Instituția Publică Complex Educațional „Ilie Fulga”",
    schoolAdress: "str. Trandafirilor 2a",
    sector: "Stăuceni",
    phone: "+373 22 455096",
    freePlaces: 100,
    freePlacesLyceum: 0,
    serviceAdress: [
      "Străzile A. Mateevici, Livezilor, Tineretului, Nistreană şi Grătieştide la  strada Păcii spre Nord; Străzile Viilor, I. Creangă, V. Alecsandri, D. Matcovschi de la drumul spre fazende spre Nord; Străzile Frunze, B.P. Haşdeu, 31 August, Nucarilor, Trandafirilor, Mioriţa, Salcîmilior, M. Eminescu, Ştefan cel Mare, Mugurel, C. Stamati, Unirii, Renaşterii, Biruinţa, Orheiului, Dacia, Dragoş – Vodă, Gheorghe Asachi, Barbu Lăutaru, Dumbravei, Decebal",
    ],
    requestsSent: 98,
    freePlacesProfiles: {
      second_tour_places: 61,
      second_tour_places_lyceum: null,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
];

const riscani2 = [
  {
    id: 24,
    name: "Instituția Publică Liceul Teoretic „Nicolae Milescu-Spătaru”",
    schoolAdress: "str. Florilor, 14/3",
    sector: "Râșcani",
    phone: "022 32 59 11",
    freePlaces: 100,
    freePlacesLyceum: 70,
    serviceAdress: [
      "Str. Studenţilor 1/1-7, 9/21, 2, 11-13 ",
      "Bd. Moscovei 11, 11/1, 11/5, 11/8, 13, 13/2, 13/3, 13/3a, 13/4, 13/5, 15, 15/1, 15/5, 15/2, 15/3, 15/6, 17/1, 17/2, 17/3, ",
      "Str. Florilor 12/1-32, 34/1 ",
      "Str. Miron Costin 1-11 ",
      "Str. M. Basarab 1/1,  2, 2/1, 4, 6",
    ],
    requestsSent: 119,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 94,
    name: "Liceul Teoretic „Mihail Sadoveanu”",
    schoolAdress: "str. Aerodromului, 5 ",
    sector: "Râșcani",
    phone: "0 22 442331",
    freePlaces: 120,
    freePlacesLyceum: 0,
    serviceAdress: [
      "Str. Tudor Vladimirescu ",
      "Str. Luncii ",
      "Str. Pajurii ",
      "Str. Macilor ",
      "Str. Dumbrava Roşie ",
      "Str. Zimbrului ",
      "Str-la Florării I, II ",
      "Str-la I Circului ",
      "Str. Corneşti ",
      "Str. Crîngului ",
      "Str. A. Saharov 6, 10, 11, 11/2, 11/3, 13",
      "Str-la Adamovici ",
      "Str-la Vadul lui Vodă 17 (a,b,c....)",
      "Str. Aerodromului",
      "Str. Florica Niţa",
      "Str. Andrei Doga ",
      "Str. Vadul lui Vodă 17",
      "Str. D. Rîşcanu 1-7, 2-20/2 ",
      "Bul. Renașterii Naționale 6, 14, 16",
      "str. Florării",
      "str. Petrăriei nr.5-21, nr. 6-28, 10",
    ],
    requestsSent: 149,
    freePlacesProfiles: {
      second_tour_places: 68,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 23,
    name: 'Liceul Teoretic „Alecu Russo"',
    schoolAdress: "str. A. Russo, 10",
    sector: "Râșcani",
    phone: "+373 22 441001",
    freePlaces: 90,
    freePlacesLyceum: 50,
    serviceAdress: [
      "Str. Dimo 11-17, 16-24 ",
      "Str. Kiev 6-16/1, 16/3, 16/4 ",
      "Str. Alecu Russo 2-8",
      "Str. Braniştii 1-9/2, 11-299",
      "Str. Kiev 2, 4",
      "Str. D. Rîşcanu 1-37 ",
    ],
    requestsSent: 68,
    freePlacesProfiles: {
      second_tour_places: 78,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 22,
    name: "Complexul Educațional (liceu-grădiniță) „Kiril şi Metodii”",
    schoolAdress: "str. Al. Haşdeu, 72",
    sector: "Râșcani",
    phone: "+373 22 544260",
    freePlaces: 60,
    freePlacesLyceum: 50,
    serviceAdress: [
      "Str.Ismail 49 până la sfârșit (impare)",
      "Str. Tighina 48-56, 67, 65 ",
      "Str.Albişoara 24-86",
      "Str. Columna 40-300 ",
      "Str. Alexandru cel Bun ",
      "Str-la Bălănescu ",
      "Str. Sf. Petru ",
      "Str. Eminescu 61-63, 70, 72 ",
      "Bd. Grigore Vieru 12-26",
      "Str. Vasile Alexandri 131-299, 88-300",
      "Str. Ioan Botezătorul ",
      "Str. Armenească 63-104, 108, 110 (pare și impare)",
      "Str. Titu Maiorescu ",
      "Str. Bulagră 99-107, 98-106 ",
      "Str. Sf. Gheorghe ",
      "Str. Cojocarilor ",
      "Str. A. Hâjdău 29-124 ",
      "Str. Habad Liubavici ",
      "Str. Octavian Goga ",
      "Str. Grigore Ureche",
      "Str. Grădinilor",
      "Str. A Puşkin 42-64; 33-53",
      "Str. Alexandru Vlahuţa ",
      "Str. Cojbuc 2-26",
      "Str. Cahul",
      "Str. Junimea",
      "Str-la Hâncu",
      "Str. Fantalului",
      "Bd Dmitrie Cantemir 57-299",
      "Str. Bălţi",
      "Str. Avram iancu",
      "Str. Sîrbească",
      "Str. Romană",
      "Str. Măzărache ",
      "Str. Sf. Ilie ",
      "Str. Zaichin ",
      "Str. Căpriana ",
      "Str. B. P. Hajdeu toată ",
      "Str. Sf. Andrei ",
      "Str. Cantonului 2-20 ",
      "Str. Ion Doncev ",
      "Str. Ion Pruncul ",
      "Str. Botezatu Andrei ",
      "Str. Petricani 1-15",
      "Str. Moara Roşie ",
      "Str. Buna Vestire ",
      "Str. Colina Puşkin ",
      "Str. Constantin Stamati 2-10 ",
      "Str. Zamfir Arbore ",
      "Str. Mirceşti ",
      "Str. Maria Cibotaru 63-69 ",
      "Str. S. Lazo 21-29, 50 ",
      "Str. Sfatul Ţării 32-300, 63-299 ",
      "Str. Columna 112-154 ",
      "Str. Bănulescu Bodoni 51-299",
      "Str. Anton Pan 9, 11 ",
      "Str. Movila lui Burcel ",
      "Str. Cramei",
      "Str. Petru Rareş ",
      "Str-la Pescaruşilor ",
      "Str-la Arhanghelul Mihail",
      "Str-la Codrul Cozminului",
      "Str. Căpriana",
      "Str. Romană",
      "Str. Buna vestire",
      "Str. Mihai Viteazul 78",
      "Str. Străşeni",
      "Str. Ipoteşti",
      "Str. A. Belski",
      "Str. Astronom Nicolae Donici",
      "Str. T Panfile",
      "Str. Memoriei",
      "Str. Valea Albă",
      "Str. Zamolxe",
      "Str. Voluntar Filip Lupaşcu",
      "Str. Volunta Gh. Vîrtosu ",
      "Str. Vasile Harea ",
      "Str. Spicului",
      "Str. Tudor Vladimirescu",
    ],
    requestsSent: 51,
    freePlacesProfiles: {
      second_tour_places: 2,
      second_tour_places_lyceum: 24,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 79,
    name: "Instituția Publică Liceul Teoretic „Ștefan cel Mare”",
    schoolAdress: "str. Florilor, 4",
    sector: "Râșcani",
    phone: "+373 22 440139",
    freePlaces: 92,
    freePlacesLyceum: 0,
    serviceAdress: [
      "Str. Bogdan Voevod ",
      "Str. Florilor 2-10 ",
      "Bd. Moscovei 1-9",
      "Str. Spartacus ",
      "Str. Valentin Roșca",
      "Str. Nadejda Russo ",
      "Str. Miron Costin 2-10 ",
      "Str. Petrăriei 54-62, 49-53",
    ],
    requestsSent: 113,
    freePlacesProfiles: {
      second_tour_places: 64,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 110,
    name: 'Instituția Publică Liceul Teoretic "Alexei Mateevici"',
    schoolAdress: "str. Tineretului, 32",
    sector: "Cricova",
    phone: "+373 22 453405",
    freePlaces: 100,
    freePlacesLyceum: 40,
    serviceAdress: [
      "Instituţia efectuează înscrierea copiilor în clasa I vorbitori de limba română din orașul Cricova",
    ],
    requestsSent: 86,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 80,
    name: "Instituția Publică Liceul Teoretic „Alexandru Ioan Cuza”",
    schoolAdress: "str. Poştei, 44",
    sector: "Râșcani",
    phone: "+373 22 468878",
    freePlaces: 112,
    freePlacesLyceum: 42,
    serviceAdress: [
      "Str. Calea Orheiului 1-107",
      "Str-la Calea Orheiului ",
      "Str. Gheorghe Madan 1-62, 2-44 ",
      "Str. Doina 1-119, 2-82 ",
      "Str. Victor Crăsesc 2-50, 1-57 ",
      "Str-la Victor Crăsescu 1-35, 2-34 ",
      "Str. 8 Martie 2-70, 1-299 ",
      "Str-la 8 Martie I ",
      "Str-la 8 Martie II ",
      "Str. Bariera Orheiului ",
      "Str. Lalelelor ",
      "Str. Liliacului ",
      "Str. Solidarităţii ",
      "Str. Criuleni 2-58, 1-65 ",
      "Str. la I Criuleni 2-38, 1-43 ",
      "Str. Pitulicii 2-24, 1-11 ",
      "Str-la Pitulicii",
      "Str. Dubăsari ",
      "Str-la Dubăsari I ",
      "Str-la Dubăsari II ",
      "Str-la Dubăsari III ",
      "Str-la Poştei ",
      "Str. Poştei",
      "Str. Podgorenilor 1-97, 2-84",
      "Str. Damian 1-58",
      "Str. C. Brîncoveanu 1-45, 2-44",
      "Str. E. Teodoroiu 1-33, 2-16",
      "Str. Timişoara 1-15, 2-18",
      "Str. Hotin 1-15, 2-34",
      "Str. Poşta Veche",
      "Str. Moldoviţa 1-19; 37 până la capăt (numere impare)",
      "Str-la Petricani I",
      "Str-la Visterniceni",
      "Str-la Cărăuşilor",
      "Str. Magda Isanos",
      "Str. Putnei 2-82, 1-79",
      "Str. Vasile Badiu",
      "Str. Constructorilor 1-299",
      "Str-la Carierei 1, 2",
      "Str. Carierei",
      "Str. Grădinarilor",
      "Str. Hipodromului",
      "Str-la V. Comarov",
      "Str. Andrei Lupan",
      "Str. Căluşari",
      "Str. Montana",
      "Str-la Doina",
      "Str-la Bulbocica I, II",
      "Str. Circului",
      "Str-la Circului ",
      "Str. Liviu Damian 1-57, 2-58",
      "Str. Spicului",
      "Str. Bulbocica",
    ],
    requestsSent: 123,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 20,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 56,
    name: 'Liceul Teoretic "Lucian Blaga"',
    schoolAdress: "str. A. Russo, 10",
    sector: "Râșcani",
    phone: "+373 22 495081",
    freePlaces: 90,
    freePlacesLyceum: 50,
    serviceAdress: [
      "Str. Dimo 1-17, 4-24 ",
      "Str. Kiev 1/3, 3/3, 2-16/1, 16/3, 16/4 ",
      "Str. Aleco Russo 2, 4, 6, 8/1, 8/2 ",
      "Str. Braniştii ",
      "Str. D. Râşcanu 9-37",
      "Str. Andrei Saharov 1, 3, 5, 2, 4, 4/3",
      "Str. Tudor Vladimirescu 18, 20, 22",
    ],
    requestsSent: 103,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 57,
    name: 'Liceul Teoretic "Natalia Gheorghiu"',
    schoolAdress: "str. Florilor, 6",
    sector: "Râșcani",
    phone: "+373 22 446123",
    freePlaces: 75,
    freePlacesLyceum: 50,
    serviceAdress: [
      "Str. Bogdan Voevod ",
      "Str. Spartacus ",
      "Str. Nadejda Russo ",
      "Bd. Moscovei 1-9 ",
      "Str. Miron Costin 2-10 ",
      "Str-la Bulbocica I",
      "Str-la Bulbocica II ",
      "Str. Hipodromului",
      "Str. Carierei",
      "Str-la Carierei I, II",
      "Str. Circului",
      "Str-la Circului ",
      "Str. Florilor 1/1, 2-10 pare",
      "Strada Petrăriei 54-62, 49-53",
      "Str. Luncii",
      "Str-la I Circului ",
      "Str. Corneşti",
      "Str. Aerodromului",
      "Str. Florica Niţa",
      "Str. Kiev 1-199",
    ],
    requestsSent: 61,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 112,
    name: "Complex Educațional „Hulboaca”",
    schoolAdress: "str. Ștefan cel Mare, 16 ",
    sector: "Hulboaca",
    phone: "+373 22 318543",
    freePlaces: 25,
    freePlacesLyceum: 0,
    serviceAdress: [
      "Instituţia efectuează înscrierea copiilor în clasa I vorbitori de limba română din satul Hulboaca",
    ],
    requestsSent: 15,
    freePlacesProfiles: {
      second_tour_places: 13,
      second_tour_places_lyceum: null,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
];

const riscani3 = [
  {
    id: 5,
    name: 'Instituția Publică Liceul Teoretic "Matei Basarab"',
    schoolAdress: "str. Matei Basarab, 14",
    sector: "Râșcani",
    phone: "+373 22 323433",
    freePlaces: 50,
    freePlacesLyceum: 0,
    serviceAdress: [
      "Str. M. Basarab 5-9, 8-16/1",
      "Str. Miron Costin - 13/1,13/2,13/3,15/1,15/2, 19/1,19/2,19/3,19/4,19/5,19/6,17/3, 21, 23",
      "Str. Dimo-21-31",
      "Bd. Moscovei 12-2 8",
      "Str. Studenţilor 10-12",
      "Str. Primar Gherman Pîntea",
      "Str-la Primar Gherman Pîntea ",
      "Str. Academician Sergiu Rădăuţanu",
      "Str. Andrei Doga",
    ],
    requestsSent: 33,
    freePlacesProfiles: {
      second_tour_places: 35,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 7,
    name: "Instituția Publică Liceul Tehnologic Resurse Educaţionale şi Trayning „Beniamin Zeev Herţli”",
    schoolAdress: "str. Dimo, 7",
    sector: "Râșcani",
    phone: "+373 22 999182",
    freePlaces: 50,
    freePlacesLyceum: 45,
    serviceAdress: [
      "Str. Macilor ",
      "Str. Dumbrava Roşie ",
      "Str. Zimbrului ",
      "Str-la Florăriei I, II ",
      "Str. Crîngului ",
      "Str. A. Saharov ",
      "Str-la Adamovici ",
      "Str. Nicolai Dimo 1- 9/1, 9/2, 9/3, 2-14 ",
      "Str-la Vadul lui Vodă ",
      "Str. Vadul lui Vodă 17  (a, b, c)",
      "Str. D. Rîşcanu 2-20/2",
      "Str. Florării",
    ],
    requestsSent: 78,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 1,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 113,
    name: 'Instituție Publică Liceul Teoretic "Dragoș Vodă"',
    schoolAdress: "str. Livezilor, 2",
    sector: "Stăuceni",
    phone: "+373 22 326754",
    freePlaces: 30,
    freePlacesLyceum: 45,
    serviceAdress: [
      "Instituţia efectuează înscrierea copiilor în clasa I din comunele Stăuceni, Goenii Noi și Vechi",
      "Str. Studenţilor nr. 2, 3, 4, 5, 6, 7, 8, 9, 10",
      "Străzile A. Mateevici, Livezilor, Grătieşti până la intersecție cu Strada Păcii",
      "Străzile Viilor, I. Creangă, V. Alecsandri, D. Matcovschi până la intersecție cu drumul spre vile. ",
    ],
    requestsSent: 44,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: 0,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 58,
    name: 'Gimnaziul cu profil teatral "Ion Luca Caragiale"',
    schoolAdress: "str. M. Costin, 19/7",
    sector: "Râșcani",
    phone: "+373 22 446329",
    freePlaces: 35,
    freePlacesLyceum: 0,
    serviceAdress: [
      "Str. Miron Costin 12-26/3, 13/1, 13/2, 13/3, 15/1, 15/2, 17/2, 17/3, 19/1, 19/2, 19/3, 19/4, 19/5, 19/6, 21, 23, 25",
      "Bd. Moscovei 2-16, 18-...pare",
      "Str. Dimo 15/1, 15/2, 19/6, 19/5, 19, 19/4, 21, 21/1, 21/2, 23, 23/2, 23/3, 25, 27/1",
      "Str. Matei Basarab 8-16, 5-9/1 ",
      "Str.Alecu Russo 1/2 până la 13/4",
    ],
    requestsSent: 53,
    freePlacesProfiles: {
      second_tour_places: 35,
      second_tour_places_lyceum: null,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 31,
    name: "Gimnaziul nr. 77",
    schoolAdress: "or. Cricova, Str. I. Creanga, 31",
    sector: "orașul Cricova",
    phone: "+373 22 453332, 060704959",
    freePlaces: 20,
    freePlacesLyceum: 0,
    serviceAdress: [
      "Instituţia efectuează înscrierea copiilor în clasa I vorbitori de limba rusă din orașul Cricova",
    ],
    requestsSent: 15,
    freePlacesProfiles: {
      second_tour_places: 6,
      second_tour_places_lyceum: null,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 26,
    name: 'Liceul Teoretic „Mihail Lomonosov"',
    schoolAdress: "str. Gh. Madan, 83",
    sector: "Râșcani",
    phone: "+373 22 460828",
    freePlaces: 75,
    freePlacesLyceum: 50,
    serviceAdress: [
      "Str. Brîncoveanu Constantin ",
      "Str. E. Teodoroiu 18-48 și 35-59 (pentru clasele în limba română)",
      "Str. Timişoara 20-46 și 17-45 (pentru clasele  în limba română)",
      "Str. Hotin 36-60 și 17-47 (pentru clasele  în limba română)",
      "Str. Putnei 68-94 și 65-91 (pentru clasele în  limba română)",
      "Str. Calea Orheiului ",
      "Str. Poştei ",
      "Str-la Poşta Veche ",
      "Str. Moldoviţa 2-18, 18a, 18b și 21-35 (pentru clasele  în limba română)",
      "Str. Magda Isanos ",
      "Str. Constructorilor ",
      "Str. L. Damian ",
      "Str-la L. Damian ",
      "Str. Iazului ",
      "Str. Gh. Madan 63-81 (pentru clasele în limba română)",
      "Str. Doina 84-100 (pentru clasele în limba română)",
      "Str. V. Crăsescu ",
      "Str-la Crăsescu ",
      "Str. 8 martie",
      "Str. Criuleni",
      "Str-la Criuleni",
      "Str-la Pitulici",
      "Str. Pitulici",
      "Str-la Criuleni",
      "Str-la Dubăsari I",
      "Str-la Dubăsari II",
      "Str-la Dubăsari III",
      "Str-la Poştei",
      "Str. Podgorenilor",
      "Str. Răzeşilor",
      "Str. Grădinarilor ",
      "Str-la Putnei",
      "Str-la 8 Martie ",
      "Str. Bariera Orheiului",
      "Str. Lalelelor",
      "Str. Liliacului",
      "Str. Solidarităţii",
      "Str. Socoleni",
      "Str-la Studenţilor",
      "Str. Ceucari",
      "Str. Grătieşti",
      "Str. Cucorilor",
      "Str. Vasile Badiu",
      "Str-la Studenţilor ",
      "Str-la Circului 40-60, 45-63 ",
      "Str-la Calea Orheiului ",
      "Str. Doina 1-119, 2-90 ",
      "Str. Dubăsari ",
      "Str. Poşta Veche",
      "Str-la Petricani I",
      "Str. Petricani",
      "Str-la Visterniceni",
      "Str-la Cărăuşilor",
      "Str. Vasile Badiu",
      "Str-la carierei 1, 2",
      "Str. Carierei",
      "Str. Hipodromului",
      "Str-la V. Comarov",
      "Str. Andrei Lupan",
      "Str. Căluşari",
      "Str. Montana",
      "Str-la Doina",
      "Str-la Bulbocica I, II",
      "Str. Circului",
      "Str-la Circului ",
      "Str. Străşeni",
      "Str. Ipoteşti",
      "Str. A. Belski",
      "Str. Astronom Nicolae Donici",
      "Str. T Panfile",
      "Str. Memoriei",
      "Str. Valea Albă",
      "Str. Zamolxe",
      "Str. Voluntar Filip Lupaşcu",
      "Str. Volunta Gh. Vîrtosu ",
      "Str. Vasile Harea ",
      "Str. Spicului",
      "Str. Timișoara 20-46 și17-45 (pentru clasele  în limba română)",
    ],
    requestsSent: 63,
    freePlacesProfiles: {
      second_tour_places: 60,
      second_tour_places_lyceum: 31,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 30,
    name: "Gimnaziul nr. 45",
    schoolAdress: "com. Ciorescu, Str. Al. cel Bun, 4",
    sector: "com. Ciorescu",
    phone: "+373 22 456274",
    freePlaces: 6,
    freePlacesLyceum: 0,
    serviceAdress: [
      "Instituţia efectuează înscrierea copiilor în clasa I vorbitori de limba rusă din comuna Ciorescu",
    ],
    requestsSent: 1,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: null,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 121,
    name: "Gimnaziul “Taras Șevcenco”",
    schoolAdress: "str. Miron Costin, 26",
    sector: "Rîșcani ",
    phone: "+373 22 445066",
    freePlaces: 25,
    freePlacesLyceum: 0,
    serviceAdress: [
      "Str.Dimo 19 - 21",
      "Bd.Moscovei 2, 8, 10, 10/1, 10/2 ",
      "Str.Alecu Russo 1/2, 3/1, 3/2, 5/1, 5/2, 7/1, 7/2, 9/1, 9/2, 11/2, 132/, 13/3, 13 ",
      "Str. Miron Costin 12-22, 26/2, 26/1, 26/3 ",
    ],
    requestsSent: 9,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: null,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
  {
    id: 120,
    name: "Școala auxiliară nr. 6 ",
    schoolAdress: "str. Miron Costin, 13/4",
    sector: "Rîșcani ",
    phone: "+373 22 541986",
    freePlaces: 12,
    freePlacesLyceum: 0,
    serviceAdress: ["f/d"],
    requestsSent: 2,
    freePlacesProfiles: {
      second_tour_places: 0,
      second_tour_places_lyceum: null,
      __typename: "FreePlacesProfiles",
    },
    __typename: "School",
  },
];

export const schoolsData = [...riscani1, ...riscani2, ...riscani3];
